// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class BookingSlotTotal
    {
        public int Id { get; set; }
        public DateTime? WorkDate { get; set; }
        public int SalonId { get; set; }
        public int HourId { get; set; }
        public int SubHourId { get; set; }
        public int Total { get; set; }
        public int StaffId { get; set; }
        public int GroupId { get; set; }
        public TimeSpan HourFrame { get; set; }
        public bool IsDelete { get; set; }
        public byte[] RowVersion { get; set; }
    }
}