// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class BookingSwitchVersion
    {
        public int Id { get; set; }
        public string Version { get; set; }
        public DateTime? CreatedTime { get; set; }
        public string TargetVersion { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}