// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class BookingRequest
    {
        public int Id { get; set; }
        public string CustomerPhone { get; set; }
        public int SalonId { get; set; }
        public int RequestStatus { get; set; }
        public string CustomerRequest { get; set; }
        public string SalonNote { get; set; }
        public bool IsBooked { get; set; }
        public int? BookingId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public bool IsDelete { get; set; }
    }
}