// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class BookingSelectedItems
    {
        public int Id { get; set; }
        public int? BookingId { get; set; }
        public int? ItemId { get; set; }
        public int? ItemType { get; set; }
        public int? SellerId { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
    }
}