// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class CustomerFeedBack
    {
        public int Id { get; set; }
        public int BillId { get; set; }
        public DateTime? CreatedBill { get; set; }
        public string StatusCall { get; set; }
        public string SalesStatus { get; set; }
        public string Agent { get; set; }
        public DateTime? CallDate { get; set; }
        public string SatisfiedService { get; set; }
        public string NoteIdeaService { get; set; }
        public string NoteHairStyle { get; set; }
        public string NoteQuality { get; set; }
        public string NoteAdvisory { get; set; }
        public string NoteServiceAttitude { get; set; }
        public string NoteLongWait { get; set; }
        public string NoteShave { get; set; }
        public string NoteNoisyStaff { get; set; }
        public string NoteOtherProblem { get; set; }
        public string DiscountCustomer { get; set; }
        public bool? IsDeleted { get; set; }
    }
}