// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class CustomerRatingDetail
    {
        public int Id { get; set; }
        public int CustomerRatingId { get; set; }
        public int AnswerId { get; set; }
        public DateTime? CreatedTime { get; set; }
    }
}