// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class DcustomerConsumeHistory
    {
        public int CustomerId { get; set; }
        public int? TotalMoneyOfBill { get; set; }
        public DateTime? DateLastOfBill { get; set; }
        public DateTime? DateFirstOfBill { get; set; }
        public int? TotalOfBill { get; set; }
        public int? IsMigrated { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string SUpdatedDate { get; set; }
    }
}