// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class DcustomerQueueInfo
    {
        public string MessageId { get; set; }
        public string MessageContent { get; set; }
        public string QueueInfo { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}