// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class DcustomerDetailBillHistory
    {
        public int CustomerId { get; set; }
        public int BillId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string StylistName { get; set; }
        public DateTime? DatedBook { get; set; }
        public int? WaitTimeInProcedure { get; set; }
        public string SalonName { get; set; }
        public string Comment { get; set; }
        public string ServiceIds { get; set; }
        public string ProductIds { get; set; }
        public double? TotalMoney { get; set; }
        public string Images { get; set; }
        public string PaymentMethod { get; set; }
        public string SkinnerName { get; set; }
    }
}