// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class DcustomerGeneralHistory
    {
        public int CustomerId { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public int? UsageNo { get; set; }
        public int? TotalCost { get; set; }
        public int? IsMigrated { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string SUpdatedDate { get; set; }
    }
}