// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class DeleteBookingBillLog
    {
        public int Id { get; set; }
        public int? BookingId { get; set; }
        public int? BillId { get; set; }
        public DateTime? CreatedTime { get; set; }
        public string DeleteNote { get; set; }
        public bool? IsDeleted { get; set; }
        public int? UserId { get; set; }
    }
}