// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class DstylistScore
    {
        public int DstylistScoreId { get; set; }
        public int? StylistId { get; set; }
        public int? Appearence { get; set; }
        public int? Communication { get; set; }
        public double? AvgScsc { get; set; }
        public DateTime? LastDateUpdate { get; set; }
        public double? AvgTimeCut { get; set; }
        public double? StylistScore { get; set; }
    }
}