// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class EquipmentSalons
    {
        public int Id { get; set; }
        public int? SalonId { get; set; }
        public int? EquipmentId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public int? SupplyerId { get; set; }
        public string Code { get; set; }
    }
}