// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class EquipmentDepartments
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DeparmentCode { get; set; }
        public bool? IsActive { get; set; }
    }
}