// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class FundOffenItem
    {
        /// <summary>
        /// Bảng danh sách các chi tiêu thường xuyên
        /// </summary>
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        /// <summary>
        /// Lượng tiền sử dụng trong khoản thu/chi này
        /// </summary>
        public int? Money { get; set; }
        public int? Order { get; set; }
        public bool? IsReceipt { get; set; }
        public int? SourceId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}