// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class GamificationGrade
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string Background { get; set; }
        public string Subtitle1 { get; set; }
        public string Subtitle2 { get; set; }
        public string Subtitle3 { get; set; }
        public int DisplayDay { get; set; }
        public bool IsDelete { get; set; }
        public string IconInactive { get; set; }
        public string BackgroundInActive { get; set; }
    }
}