// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class IvInventoryCurrentLog
    {
        public int Id { get; set; }
        public int InventoryCurrentId { get; set; }
        public int InventoryId { get; set; }
        public int ProductId { get; set; }
        public int? BeginOld { get; set; }
        public int? BeginNew { get; set; }
        public DateTime AccountingDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}