// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class IvInventoryCurrentTrace
    {
        public int Id { get; set; }
        public int? InventoryId { get; set; }
        public int? ProductId { get; set; }
        public decimal? MaxInventorySuggest { get; set; }
        public decimal? UsedEnd { get; set; }
        public bool? IsOrder { get; set; }
        public DateTime? AccountingDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool IsDelete { get; set; }
        public int? InventoryCurrentId { get; set; }
        public bool? IsEnough { get; set; }
        public string TypeCheck { get; set; }
    }
}