// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class IvProductQuantify
    {
        public int Id { get; set; }
        public int? InventoryId { get; set; }
        public int? ServiceId { get; set; }
        public int? ProductId { get; set; }
        public int? StaffType { get; set; }
        public double? Volume { get; set; }
        public int? TotalNumberService { get; set; }
        public double? Quantify { get; set; }
        public bool? IsPublish { get; set; }
        public bool IsDelete { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}