// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class IvProductQuantifyV2
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public int? Volume { get; set; }
        public int? Quantify { get; set; }
        public int? ConsumptionType { get; set; }
        public byte? IsBase { get; set; }
        public byte? IsDisplaySkinnerApp { get; set; }
        public byte? IsDelete { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}