// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class LockBlock
    {
        public DateTime Date { get; set; }
        public short BlockedSessionId { get; set; }
        public short BlockingSessionId { get; set; }
        public string BlockedSessionTsql { get; set; }
        public string BlockingSessionTsql { get; set; }
        public byte[] BlockedSessionSqlhandle { get; set; }
        public byte[] BlockingSessionSqlhandle { get; set; }
        public string BlockingSessionLoginName { get; set; }
        public string BlockingSessionApplicationName { get; set; }
        public string BlockingSessionHostName { get; set; }
    }
}