// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class MemberLog
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Phone { get; set; }
        public int ProductId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int Amount { get; set; }
        public int? IsDelete { get; set; }
        public int BillId { get; set; }
        public int? Type { get; set; }
        public bool? IsSuccess { get; set; }
        public string CustomerName { get; set; }
        public bool IsCancel { get; set; }
        public string Note { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? MemberBuyType { get; set; }
        public bool? IsChecked { get; set; }
        public bool? CheckResult { get; set; }
        public bool? BuyProduct { get; set; }
        public string ProductDetail { get; set; }
    }
}