// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class MktCampaignBill
    {
        public int Id { get; set; }
        public int CampaignId { get; set; }
        public int BillId { get; set; }
        public double DiscountMoney { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public bool IsDelete { get; set; }
        public int ServiceId { get; set; }
        public int? MoneyPrePaid { get; set; }
        public int? MoneyDeductions { get; set; }
        public int? ProductId { get; set; }
        public int? UsingCampaignInProduct { get; set; }
    }
}