// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class OrderBrokenDeviceHandlingLog
    {
        public int Id { get; set; }
        public int? OrderBrokenDeviceId { get; set; }
        public int? TypeId { get; set; }
        public int StaffEditId { get; set; }
        public string Value { get; set; }
        public DateTime? CreatedTime { get; set; }
    }
}