// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class RatingAnswer
    {
        public int Id { get; set; }
        public string Answer { get; set; }
        public DateTime CreatedTime { get; set; }
        public bool? IsDeleted { get; set; }
        public int Type { get; set; }
        public bool? Positive { get; set; }
    }
}