// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class RatingConfigPoint
    {
        public int Id { get; set; }
        /// <summary>
        /// Điểm được lưu vào bill, ví dụ từ 1 -&gt; 5
        /// </summary>
        public int? RealPoint { get; set; }
        /// <summary>
        /// Điểm quy ước, ví dụ : điểm lưu vào bill là 1, quy ước là 0. 2|3, 3|10
        /// </summary>
        public double? ConventionPoint { get; set; }
        /// <summary>
        /// Tên gọi mức điểm, ví dụ : 1(0 theo quy ước) | Không hài lòng, 2 | Hài lòng, 3 | Rất hài lòng
        /// </summary>
        public string ConventionName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? IsDelete { get; set; }
        public int? Status { get; set; }
        /// <summary>
        /// Chỉ dấu : 1|Bộ quy ước điểm đánh giá nhân viên từ khách theo bill, 2|Bộ quy ước điểm đánh giá nhân viên từ khảo sát
        /// </summary>
        public int? Hint { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}