// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class SalonEquipmentChange
    {
        public int Id { get; set; }
        public int? EquipmentId { get; set; }
        public int? StaffId { get; set; }
        public DateTime? CreatedTime { get; set; }
        public bool? IsDeleted { get; set; }
    }
}