// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class ScscSalonStaffCheckError
    {
        public int Id { get; set; }
        public int? SalonId { get; set; }
        public int? StaffId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public DateTime? WorkDate { get; set; }
        public bool? IsDefault { get; set; }
        public string Reason { get; set; }
        public string WorkWeek { get; set; }
    }
}