// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class ServiceWorkflowStep
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? WorkflowId { get; set; }
        public string Description { get; set; }
        public int? Duration { get; set; }
        public string MediaUrl { get; set; }
        public DateTime? CreatedTime { get; set; }
        public bool? IsDeleted { get; set; }
    }
}