// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StaffWorkingState
    {
        public int StaffId { get; set; }
        public DateTime WorkDate { get; set; }
        public int? WorkHours { get; set; }
        public int? ServedCustomers { get; set; }

        public virtual Staff Staff { get; set; }
    }
}