// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StaffTarget
    {
        public int Id { get; set; }
        public DateTime? WorkDate { get; set; }
        public int? SalonId { get; set; }
        public int? StaffId { get; set; }
        public double Kpidistribution { get; set; }
        public long? Type { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifielTime { get; set; }
        public bool? IsDelete { get; set; }
    }
}