// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StaffSalonHistory
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public int OlderSalonId { get; set; }
        public int CurrentSalonId { get; set; }
        public DateTime? TransferDate { get; set; }
        public bool? IsDelete { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}