// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StaffApprovalInfo
    {
        public int Id { get; set; }
        public int StaffId { get; set; }
        public string Data { get; set; }
        public int StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public int? ApproveUserId { get; set; }
        public int Type { get; set; }
    }
}