// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StatisticRating
    {
        public int StaffId { get; set; }
        public DateTime WorkDate { get; set; }
        public int AnswerId { get; set; }
        public int Count { get; set; }
        public int Type { get; set; }
    }
}