// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StoreQrScan
    {
        public int Id { get; set; }
        public int? BillId { get; set; }
        public string MacAddress { get; set; }
        public DateTime? ScanDate { get; set; }
        public int? ScanDateInt { get; set; }
        public string ScanDateString { get; set; }
        public string Salon { get; set; }
        public int? StylistId { get; set; }
    }
}