// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class Stylist4MenClass
    {
        public int Id { get; set; }
        /// <summary>
        /// Tên lớp học
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Ghi chú
        /// </summary>
        public string Note { get; set; }
        /// <summary>
        /// Ngày bắt đầu (Khai giảng)
        /// </summary>
        public DateTime? StartTime { get; set; }
        /// <summary>
        /// Ngày tốt nghiệp (Hoàn thành khóa học)
        /// </summary>
        public DateTime? GraduateTime { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        /// <summary>
        /// Thời gian tạo bản ghi
        /// </summary>
        public DateTime? CreatedTime { get; set; }
        /// <summary>
        /// Thời gian sửa lần gần nhất
        /// </summary>
        public DateTime? ModifiedTime { get; set; }
        /// <summary>
        /// Trụ sở đào tạo (Sẽ ở 1 salon nào đó)
        /// </summary>
        public int? SalonId { get; set; }
        public int? HomeRoomTeacherId { get; set; }
        public int? TeacherPointCutId { get; set; }
        public int? TeacherOfTheClubId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}