// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StynextServiceSalaryConfig
    {
        public int Id { get; set; }
        public int? SalonId { get; set; }
        public int? DepartmentId { get; set; }
        public int? ServiceId { get; set; }
        public int? LevelId { get; set; }
        public double? ServiceSalary { get; set; }
        public double? ServiceBonus { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}