// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class StynextLevelConfig
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? StaffType { get; set; }
        public double ServiceCommissionPercent { get; set; }
        public double RatioOvertimeHour { get; set; }
        public double RatioOvertimeDay { get; set; }
        public double GroupCommissionPercent { get; set; }
        public double FixedSalary { get; set; }
        public double RevenueTargetStandard { get; set; }
        public double R30targetStandard { get; set; }
        public double BehaveSalary { get; set; }
        public int? Type { get; set; }
    }
}