// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class SurveyContent
    {
        public int Id { get; set; }
        public int? Pid { get; set; }
        /// <summary>
        /// Nội dung
        /// </summary>
        public string Content { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// Danh mục khảo sát
        /// </summary>
        public int? CategoryId { get; set; }
        public bool? Correct { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool IsDelete { get; set; }
        public bool? Publish { get; set; }
        public bool? Featured { get; set; }
        public int? Order { get; set; }
        /// <summary>
        /// Là câu hỏi hay câu trả lời : True | Câu hỏi, False | Câu trả lời
        /// </summary>
        public bool IsQuestion { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}