// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class TblPermission
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PTitle { get; set; }
        public int? POder { get; set; }
        public bool? PPublish { get; set; }
        public DateTime? PCreatedDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}