// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class TblPermissionAction
    {
        public int AId { get; set; }
        public string AName { get; set; }
        public string ADescription { get; set; }
        public bool? APublish { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}