// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DB201990809
{
    public partial class TblTesst
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public bool? Issms { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}