// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("Api_Video")]
    public partial class ApiVideo
    {
        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        public string Link { get; set; }
        [StringLength(250)]
        public string Title { get; set; }
        [Column(TypeName = "ntext")]
        public string Description { get; set; }
        [StringLength(250)]
        public string Thumb { get; set; }
        public long? ViewCount { get; set; }
        public long? CommentCount { get; set; }
        public long? DislikeCount { get; set; }
        public long? LikeCount { get; set; }
        public bool? IsDelete { get; set; }
        public bool? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateChanged { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PublishDate { get; set; }
        [StringLength(250)]
        public string VideoId { get; set; }
        [StringLength(250)]
        public string Chanel { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}