// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("BookHour_2ndSub")]
    public partial class BookHour2ndSub
    {
        [Key]
        public int Id { get; set; }
        public int HourId { get; set; }
        public int SubHourId { get; set; }
        public int SecondSubHourId { get; set; }
        [Required]
        [StringLength(20)]
        public string Hour { get; set; }
        [Column(TypeName = "time(0)")]
        public TimeSpan HourFrame { get; set; }
        public int SalonId { get; set; }
        [Required]
        public bool? Publish { get; set; }
        public bool IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
    }
}