// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class BookingLog
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(15)]
        public string CustomerPhone { get; set; }
        public int HourId { get; set; }
        public int SubHourId { get; set; }
        public int SalonId { get; set; }
        public int StylistId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BookDate { get; set; }
        [Column("OS")]
        public int Os { get; set; }
        public bool IsBookStylist { get; set; }
        [StringLength(450)]
        public string TextNote1 { get; set; }
        [StringLength(450)]
        public string TextNote2 { get; set; }
        public bool IsEnterVoucher { get; set; }
        public bool IsUseVoucher { get; set; }
        public int? BookingId { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public int? SecondSubHourId { get; set; }
    }
}