// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class BookingSlotAvailable
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        public int SalonId { get; set; }
        public int HourId { get; set; }
        public int SubHourId { get; set; }
        public int Available { get; set; }
        public int GroupId { get; set; }
        public int StylistId { get; set; }
        public TimeSpan HourFrame { get; set; }
        public bool IsDelete { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }
    }
}