// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class CheckinCheckout
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckinTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckoutTime { get; set; }
        public int? SalonId { get; set; }
        public int? StaffId { get; set; }
        public int? FlowTimeKeepingId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        public bool? IsDelete { get; set; }
        [StringLength(300)]
        public string UniqueKey { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        public bool? IsComeLateConfirm { get; set; }
        public bool? IsLeaveEarlyConfirm { get; set; }
        public bool? IsLeaveEarly { get; set; }
        public bool? IsComeLate { get; set; }
    }
}