// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("Customer_Booking_Check")]
    public partial class CustomerBookingCheck
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("BookingID")]
        public int BookingId { get; set; }
        [Column("CustomerID")]
        public int CustomerId { get; set; }
        [Column("SalonID")]
        public int SalonId { get; set; }
        public bool IsCall { get; set; }
        public int Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        [StringLength(450)]
        public string Note { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}