// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("DCustomerGeneralHistory")]
    public partial class DcustomerGeneralHistory
    {
        [Key]
        public int CustomerId { get; set; }
        [Key]
        public int Type { get; set; }
        [Key]
        [StringLength(1000)]
        public string Name { get; set; }
        public int? UsageNo { get; set; }
        public int? TotalCost { get; set; }
        public int? IsMigrated { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [Column("sUpdatedDate")]
        [StringLength(64)]
        public string SUpdatedDate { get; set; }
    }
}