// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("DCustomerCall")]
    public partial class DcustomerCall
    {
        [Key]
        public int IdCustomerCall { get; set; }
        public int? CustomerId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DatetimeCall { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartTimeCall { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndCallTime { get; set; }
        public int? TypeOfCallId { get; set; }
        public int? ResultOfCallId { get; set; }
        [StringLength(250)]
        public string NoteOfCall { get; set; }
        [Column("DeviceIMEI")]
        [StringLength(200)]
        public string DeviceImei { get; set; }
        public int? SalonId { get; set; }
        public int? DepartmentId { get; set; }
        public int? StaffId { get; set; }
        public int? CallId { get; set; }
        public int? BookingId { get; set; }
    }
}