// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("DCustomerDetailBillHistory")]
    public partial class DcustomerDetailBillHistory
    {
        [Key]
        public int CustomerId { get; set; }
        [Key]
        public int BillId { get; set; }
        public DateTime? CreatedDate { get; set; }
        [StringLength(200)]
        public string StylistName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DatedBook { get; set; }
        public int? WaitTimeInProcedure { get; set; }
        [StringLength(300)]
        public string SalonName { get; set; }
        [StringLength(200)]
        public string Comment { get; set; }
        [StringLength(1000)]
        public string ServiceIds { get; set; }
        [StringLength(1000)]
        public string ProductIds { get; set; }
        public double? TotalMoney { get; set; }
        [StringLength(2000)]
        public string Images { get; set; }
        [StringLength(600)]
        public string PaymentMethod { get; set; }
        [StringLength(200)]
        public string SkinnerName { get; set; }
    }
}