// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class DeleteBookingBillLog
    {
        [Key]
        public int Id { get; set; }
        public int? BookingId { get; set; }
        public int? BillId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [StringLength(500)]
        public string DeleteNote { get; set; }
        public bool? IsDeleted { get; set; }
        public int? UserId { get; set; }
    }
}