// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class Equipments
    {
        [Key]
        public int Id { get; set; }
        public int? GroupId { get; set; }
        public int? DeparmentId { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [StringLength(20)]
        public string EquipmentCode { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsInSalon { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
    }
}