// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("ERP.CheckCSVC")]
    public partial class ErpCheckCsvc
    {
        [Key]
        public int Id { get; set; }
        public int? ItemId { get; set; }
        [StringLength(250)]
        public string Comment { get; set; }
        [Column(TypeName = "text")]
        public string Image { get; set; }
        public int? StaffId { get; set; }
        public int? SalonId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateTime { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        public int? CreatorId { get; set; }
        public bool? IsOk { get; set; }
        public bool? IsReported { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FixDate { get; set; }
        public int? FixStaffId { get; set; }
        public int? Status { get; set; }
        public int? Time { get; set; }
        public int? DoingStaffId { get; set; }
        public int? ConfirmStaffId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DoingCreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ConfirmCreateDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}