// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class GamificationQuestStaff
    {
        [Key]
        public int Id { get; set; }
        public int QuestId { get; set; }
        public int StaffId { get; set; }
        public int Status { get; set; }
        [StringLength(20)]
        public string Progress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Deadline { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndTime { get; set; }
        public bool IsDelete { get; set; }
        public bool GetReward { get; set; }
        public bool IsAccepted { get; set; }
    }
}