// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class GamificationGrade
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(250)]
        public string Icon { get; set; }
        [StringLength(250)]
        public string Background { get; set; }
        [StringLength(250)]
        public string Subtitle1 { get; set; }
        [StringLength(250)]
        public string Subtitle2 { get; set; }
        [StringLength(250)]
        public string Subtitle3 { get; set; }
        public int DisplayDay { get; set; }
        public bool IsDelete { get; set; }
        [StringLength(250)]
        public string IconInactive { get; set; }
        [StringLength(250)]
        public string BackgroundInActive { get; set; }
    }
}