// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class GamificationQuest
    {
        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(200)]
        public string CategoryName { get; set; }
        public int Type { get; set; }
        public int Point { get; set; }
        [StringLength(500)]
        public string Condition { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        [StringLength(300)]
        public string Icon { get; set; }
        public int? GradeId { get; set; }
        public bool IsDelete { get; set; }
        public int? Loop { get; set; }
    }
}