// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("Inventory_Flow_HC")]
    public partial class InventoryFlowHc
    {
        [Key]
        public int Id { get; set; }
        [Column("InvenID")]
        public int? InvenId { get; set; }
        public int? ProductId { get; set; }
        public double? Quantity { get; set; }
        public int? Cost { get; set; }
        public int? Price { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public bool? IsDelete { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}