// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class IvInventoryLog
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("InventoryID")]
        public int? InventoryId { get; set; }
        [Column("ProductID")]
        public int? ProductId { get; set; }
        [Column("BillID")]
        public int? BillId { get; set; }
        public int? Quantity { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        [StringLength(1000)]
        public string Note { get; set; }
    }
}