// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class IvInventoryMaxService
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProductID")]
        public int? ProductId { get; set; }
        [Column("InventoryID")]
        public int? InventoryId { get; set; }
        public int? InvMaxDay { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? InvMaxOld { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? InvMaxSugges { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? InvMaxUser { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
    }
}