// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class IvInventoryCheckLog
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("InventoryID")]
        public int? InventoryId { get; set; }
        [Column("ProductID")]
        public int? ProductId { get; set; }
        public int? End { get; set; }
        public int? Negative { get; set; }
        public int? Positive { get; set; }
        public int? Checktime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
    }
}