// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class IvInventoryCurrentLog
    {
        [Key]
        public int Id { get; set; }
        public int InventoryCurrentId { get; set; }
        public int InventoryId { get; set; }
        public int ProductId { get; set; }
        public int? BeginOld { get; set; }
        public int? BeginNew { get; set; }
        [Column(TypeName = "date")]
        public DateTime AccountingDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}