// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("KetQuaKinhDoanh_FlowImport")]
    public partial class KetQuaKinhDoanhFlowImport
    {
        [Key]
        public int Id { get; set; }
        [Column("KQKDSalonId")]
        public int? KqkdsalonId { get; set; }
        [Column("KQKDItemId")]
        public int? KqkditemId { get; set; }
        public long? Value { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ImportDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public bool? IsDelete { get; set; }
        [StringLength(600)]
        public string Note { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}