// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    /// <summary>
    /// Danh sach tieu chi
    /// </summary>
    [Table("KPI_Criterias")]
    public partial class KpiCriterias
    {
        [Key]
        public int Id { get; set; }
        [Column("Staff_TypeId")]
        public int? StaffTypeId { get; set; }
        [Column("Criteria_Name")]
        [StringLength(250)]
        public string CriteriaName { get; set; }
        public string Formula { get; set; }
        [Column("Calculated_Weight")]
        public int? CalculatedWeight { get; set; }
        [StringLength(10)]
        public string Point { get; set; }
        public byte? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        [Column("Criteria_Code")]
        [StringLength(50)]
        public string CriteriaCode { get; set; }
    }
}