// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("KPI_Data_Days")]
    public partial class KpiDataDays
    {
        [Key]
        public int Id { get; set; }
        [Column("Staff_Id")]
        public int? StaffId { get; set; }
        [Column("Skill_LevelId")]
        public int? SkillLevelId { get; set; }
        [Column("Salon_Id")]
        public int? SalonId { get; set; }
        [Column("Staff_Type_Id")]
        public int? StaffTypeId { get; set; }
        public int? TongBill { get; set; }
        [Column("KH_Moi")]
        public double? KhMoi { get; set; }
        [Column("RatingTB")]
        public double? RatingTb { get; set; }
        [Column("KPI_RatingTB")]
        [StringLength(50)]
        public string KpiRatingTb { get; set; }
        public double? BillKhongAnh { get; set; }
        [Column("KPI_BillKhongAnh")]
        [StringLength(50)]
        public string KpiBillKhongAnh { get; set; }
        [Column("Bill_Mo_lech")]
        public double? BillMoLech { get; set; }
        [Column("KPI_Bill_Mo_lech")]
        [StringLength(50)]
        public string KpiBillMoLech { get; set; }
        [Column("SCSC_TB")]
        public double? ScscTb { get; set; }
        [Column("KPI_SCSC_TB")]
        [StringLength(50)]
        public string KpiScscTb { get; set; }
        [Column("GS_Loi")]
        public double? GsLoi { get; set; }
        [Column("KPI_GS_Loi")]
        [StringLength(50)]
        public string KpiGsLoi { get; set; }
        [Column("CMT")]
        public double? Cmt { get; set; }
        [Column("KPI_CMT")]
        [StringLength(50)]
        public string KpiCmt { get; set; }
        [Column("GT_KH_Moi")]
        public double? GtKhMoi { get; set; }
        [Column("KPI_GT_KH_Moi")]
        [StringLength(50)]
        public string KpiGtKhMoi { get; set; }
        public double? ChoLau { get; set; }
        [Column("KPI_ChoLau")]
        [StringLength(50)]
        public string KpiChoLau { get; set; }
        public int? SoKhachCanGoi { get; set; }
        public int? DaGoi { get; set; }
        public double? GoiNhacKhach { get; set; }
        [Column("KPI_GoiNhacKhach")]
        [StringLength(50)]
        public string KpiGoiNhacKhach { get; set; }
        [Column("ThuongDV")]
        public double? ThuongDv { get; set; }
        [Column("ThuongSP")]
        public double? ThuongSp { get; set; }
        public double? LuongCung { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedDate { get; set; }
        [Column("KPI_Range")]
        [StringLength(50)]
        public string KpiRange { get; set; }
        [Column("KPI_Point")]
        public double? KpiPoint { get; set; }
        public double? DoanhThu { get; set; }
        [Column("KPI_DoanhThu")]
        [StringLength(50)]
        public string KpiDoanhThu { get; set; }
        [Column("KPI_DoanhThu_Day")]
        public double? KpiDoanhThuDay { get; set; }
        public int? TotalRating { get; set; }
        [Column("TotalPointSCSC")]
        public int? TotalPointScsc { get; set; }
        public int? TotalBillDanhGiaNotImageMoLech { get; set; }
        public double? TempSalary { get; set; }
        public double? QuyTrinh { get; set; }
        [Column("KPI_QuyTrinh")]
        [StringLength(50)]
        public string KpiQuyTrinh { get; set; }
    }
}