// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("KPI_Detail_Ratings")]
    public partial class KpiDetailRatings
    {
        [Key]
        public int Id { get; set; }
        [Column("Staff_Id")]
        public int? StaffId { get; set; }
        [Column("Star_1")]
        public int? Star1 { get; set; }
        [Column("Star_2")]
        public int? Star2 { get; set; }
        [Column("Star_3")]
        public int? Star3 { get; set; }
        [Column("Star_4")]
        public int? Star4 { get; set; }
        [Column("Star_5")]
        public int? Star5 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
    }
}