// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    /// <summary>
    /// Dinh muc cho salon
    /// </summary>
    [Table("KPI_Salons")]
    public partial class KpiSalons
    {
        [Key]
        public int Id { get; set; }
        public int? SalonId { get; set; }
        [Column("KPI")]
        public double? Kpi { get; set; }
        [Column("KPI_Month", TypeName = "datetime")]
        public DateTime? KpiMonth { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
    }
}