// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class Log
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LogTime { get; set; }
        public string Content { get; set; }
        [Column("OBJId")]
        public int? Objid { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        public int? Status { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        [Column("userId")]
        public int? UserId { get; set; }
    }
}