// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("Marketing_Chiphingay")]
    public partial class MarketingChiphingay
    {
        [Key]
        public int Id { get; set; }
        [Column("Item_Id")]
        public int? ItemId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayChi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifileDate { get; set; }
        public bool? IsDelete { get; set; }
        [Column("Staff_Id")]
        public int? StaffId { get; set; }
        public int? SalonId { get; set; }
        [Column(TypeName = "decimal(20, 0)")]
        public decimal? GiaTri { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}