// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class MemberLog
    {
        [Key]
        public int Id { get; set; }
        public int CustomerId { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        public int ProductId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndTime { get; set; }
        [Column("amount")]
        public int Amount { get; set; }
        [Column("isDelete")]
        public int? IsDelete { get; set; }
        public int BillId { get; set; }
        public int? Type { get; set; }
        public bool? IsSuccess { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public bool IsCancel { get; set; }
        [StringLength(250)]
        public string Note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public int? MemberBuyType { get; set; }
        public bool? IsChecked { get; set; }
        public bool? CheckResult { get; set; }
        public bool? BuyProduct { get; set; }
        [StringLength(500)]
        public string ProductDetail { get; set; }
    }
}