// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class Message
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeleteTime { get; set; }
        public int? SenderId { get; set; }
        public int? ReceiverId { get; set; }
        public bool? IsAutoGenerate { get; set; }
        [Column(TypeName = "nvarchar(max)")]
        public string Text { get; set; }
        public int? Seq { get; set; }
        [StringLength(50)]
        public string Sender { get; set; }
        public bool? Status { get; set; }
        [StringLength(50)]
        public string Receiver { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendTime { get; set; }
        public bool? IsDelete { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendSuccessTime { get; set; }
        [StringLength(50)]
        public string Salon { get; set; }
        public int? SalonId { get; set; }
        public int? Type { get; set; }
    }
}