// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class Mobile
    {
        [Key]
        public int Id { get; set; }
        public int? AndroidVersion { get; set; }
        [Column("IOSVersion")]
        [StringLength(50)]
        public string Iosversion { get; set; }
        [StringLength(50)]
        public string AccessKey { get; set; }
        [StringLength(50)]
        public string PrivateKey { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool IsDelete { get; set; }
        [StringLength(20)]
        public string AppKey { get; set; }
        public int? AppReview { get; set; }
    }
}