// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class MonitorStaffError
    {
        [Key]
        public int Id { get; set; }
        public int ReporterId { get; set; }
        public int? SalonId { get; set; }
        public int? StaffTypeId { get; set; }
        public int? StaffId { get; set; }
        public int? HandleId { get; set; }
        [Required]
        [Column(TypeName = "nvarchar(max)")]
        public string Images { get; set; }
        public int CategoryRootId { get; set; }
        public int CategorySubId { get; set; }
        [Required]
        [Column(TypeName = "nvarchar(max)")]
        public string NoteByReporter { get; set; }
        public int? ReviewerId { get; set; }
        [Column(TypeName = "nvarchar(max)")]
        public string NoteByReviewer { get; set; }
        public bool IsPending { get; set; }
        public bool IsCommit { get; set; }
        public int StatusError { get; set; }
        public int? ResolverId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ResolveTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ConfirmTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommitTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyDate { get; set; }
        public bool IsDelete { get; set; }
        public int? PeriodBeforeConfirm { get; set; }
        public int? PeriodBeforeCommit { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ErrorTime { get; set; }
        public int? ErpStaffTypeId { get; set; }
        public bool? IsView { get; set; }
        public int? ErpErrorHandle { get; set; }
        public int? NumInspect { get; set; }
        public string AcceptanceImages { get; set; }
        [StringLength(500)]
        public string NoteByQualityManager { get; set; }
    }
}