// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("ProductReturn_Explanation")]
    public partial class ProductReturnExplanation
    {
        [Key]
        public int Id { get; set; }
        [Column("BillID")]
        public int? BillId { get; set; }
        public int? FlowProductId { get; set; }
        public int? SalonId { get; set; }
        public int? ProductId { get; set; }
        public int? InventoryId { get; set; }
        /// <summary>
        /// 0: Giải trình, 1: Đang chờ duyệt, 2: Chấp nhận, 3: Giải trình lại,4: Không chấp nhận, 5: Đã trả hàng
        /// </summary>
        public int? Status { get; set; }
        [Column("Note_Salon")]
        [StringLength(500)]
        public string NoteSalon { get; set; }
        [Column("Note_KeToan")]
        [StringLength(500)]
        public string NoteKeToan { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreateDateBill { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [StringLength(50)]
        public string CreatedUser { get; set; }
        [StringLength(50)]
        public string UpdateUser { get; set; }
        [StringLength(50)]
        public string CreateAcounter { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AcounterCreateDate { get; set; }
        public int? Quantity { get; set; }
        public int? NumberProductReturn { get; set; }
        public int? CountReturn { get; set; }
    }
}