// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class ProductUsedStatistic
    {
        [Key]
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? ServiceId { get; set; }
        public int? ProductId { get; set; }
        public double? QuantifyDefault { get; set; }
        public double? Quantify { get; set; }
        [StringLength(50)]
        public string SlugKey { get; set; }
        public int? OrderNumber { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        public int? Status { get; set; }
        public bool IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
    }
}