// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class SalaryIncomeChange
    {
        [Key]
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? SalonId { get; set; }
        [StringLength(200)]
        public string ChangedType { get; set; }
        public int? ChangedTypeId { get; set; }
        [Column(TypeName = "nvarchar(max)")]
        public string Description { get; set; }
        [StringLength(300)]
        public string Images { get; set; }
        public int? Point { get; set; }
        public int? ScoreFactor { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public bool? IsDeleted { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}