// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("SM_BillTemp")]
    public partial class SmBillTemp
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Salon ID
        /// </summary>
        public int? SalonId { get; set; }
        /// <summary>
        /// Khách hàng ID
        /// </summary>
        public int? CustomerId { get; set; }
        /// <summary>
        /// Booking ID
        /// </summary>
        public int? BookingId { get; set; }
        /// <summary>
        /// Stylist ID
        /// </summary>
        [Column("Staff_Hairdresser_Id")]
        public int? StaffHairdresserId { get; set; }
        /// <summary>
        /// Skinner ID
        /// </summary>
        [Column("Staff_HairMassage_Id")]
        public int? StaffHairMassageId { get; set; }
        /// <summary>
        /// Lễ tân (Checkin) ID
        /// </summary>
        public int? ReceptionId { get; set; }
        /// <summary>
        /// NV bán mỹ phẩm ID
        /// </summary>
        public int? SellerId { get; set; }
        /// <summary>
        /// JSON mảng Dịch vụ
        /// </summary>
        public string ServiceIds { get; set; }
        /// <summary>
        /// JSON mảng Sản phẩm
        /// </summary>
        public string ProductIds { get; set; }
        /// <summary>
        /// Tổng số tiền
        /// </summary>
        public int? TotalMoney { get; set; }
        /// <summary>
        /// Điểm đánh giá
        /// </summary>
        public int? Mark { get; set; }
        /// <summary>
        /// Ảnh khách hàng
        /// </summary>
        [StringLength(600)]
        public string Images { get; set; }
        /// <summary>
        /// Ghi chú
        /// </summary>
        [Column(TypeName = "ntext")]
        public string Note { get; set; }
        /// <summary>
        /// Mốc thời gian khách bắt đầu bước vào quy trình gội, cắt (Tính từ khi skinner gội đầu và nhập mã nhân viên trên app Staff 30S)
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? InProcedureTime { get; set; }
        /// <summary>
        /// Thời gian sửa mốc khách vào gội lần cuối cùng
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? InProcedureTimeModifed { get; set; }
        public byte? IsDelete { get; set; }
        public DateTime? ModifiedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompleteBillTime { get; set; }
        [StringLength(20)]
        public string BillCode { get; set; }
        [Column("PDFBillCode")]
        [StringLength(30)]
        public string PdfbillCode { get; set; }
        public int? TeamId { get; set; }
        public byte? Status { get; set; }
        [Column("VIPCard")]
        public bool? Vipcard { get; set; }
        [Column("VIPCardGive")]
        [StringLength(10)]
        public string VipcardGive { get; set; }
        [Column("VIPCardUse")]
        [StringLength(10)]
        public string VipcardUse { get; set; }
        /// <summary>
        /// Trạng thái bill có phải online hay ko
        /// </summary>
        public bool? IsOnline { get; set; }
        /// <summary>
        /// Phương thức thanh toán ID
        /// </summary>
        public int? PayMethodId { get; set; }
        /// <summary>
        /// Trạng thái đã thanh toán hay chưa
        /// </summary>
        public bool? Paid { get; set; }
        public int? BillStatusId { get; set; }
        /// <summary>
        /// Phí COD (trả cho đối tác vận chuyển) - Bán hàng online
        /// </summary>
        [Column("FeeCOD")]
        public int? FeeCod { get; set; }
        /// <summary>
        /// Phí thu thêm (Áp dụng cho bán hàng online, có thể là tiền vận chuyển)
        /// </summary>
        public int? FeeExtra { get; set; }
        /// <summary>
        /// Khách có thanh toán bằng Card hay ko
        /// </summary>
        public bool? IsPayByCard { get; set; }
        /// <summary>
        /// Có tính nhân đôi cho nhân viên hay không
        /// </summary>
        public bool? IsX2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("HCItem")]
        [StringLength(50)]
        public string Hcitem { get; set; }
        [Column("BillServiceID")]
        public int? BillServiceId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}