// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("SM_BillTemp_FlowService")]
    public partial class SmBillTempFlowService
    {
        [Key]
        public int Id { get; set; }
        public int? BillId { get; set; }
        public int? ServiceId { get; set; }
        public int? Price { get; set; }
        public DateTime? CreatedDate { get; set; }
        public byte? IsDelete { get; set; }
        public int? Quantity { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? SalonId { get; set; }
        public int? SellerId { get; set; }
        public double? VoucherPercent { get; set; }
        public byte? CoefficientRating { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}