// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("_staff_working_state")]
    public partial class StaffWorkingState
    {
        [Key]
        [Column("staff_id")]
        public int StaffId { get; set; }
        [Key]
        [Column("work_date", TypeName = "date")]
        public DateTime WorkDate { get; set; }
        [Column("work_hours")]
        public int? WorkHours { get; set; }
        [Column("served_customers")]
        public int? ServedCustomers { get; set; }

        [ForeignKey(nameof(StaffId))]
        [InverseProperty("StaffWorkingState")]
        public virtual Staff Staff { get; set; }
    }
}