// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class Staff
    {
        public Staff()
        {
            StaffWorkingState = new HashSet<StaffWorkingState>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(10)]
        public string Code { get; set; }
        [Column(TypeName = "date")]
        public DateTime? BirthDay { get; set; }
        public byte? Gender { get; set; }
        public int? Type { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        public int? Position { get; set; }
        public int? IdShowroom { get; set; }
        public DateTime? CreatedDate { get; set; }
        public byte? Active { get; set; }
        [StringLength(200)]
        public string Fullname { get; set; }
        [Column("SN_day")]
        public int? SnDay { get; set; }
        [Column("SN_month")]
        public int? SnMonth { get; set; }
        [Column("SN_year")]
        public int? SnYear { get; set; }
        public int? CityId { get; set; }
        public int? DistrictId { get; set; }
        [StringLength(600)]
        public string Address { get; set; }
        public byte? IsDelete { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(50)]
        public string Permission { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? SalonId { get; set; }
        public int? SkillLevel { get; set; }
        [Column("StaffID")]
        [StringLength(50)]
        public string StaffId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateJoin { get; set; }
        [StringLength(10)]
        public string OrderCode { get; set; }
        public string FingerTemplate { get; set; }
        [StringLength(20)]
        public string FingerToken { get; set; }
        [Column(TypeName = "ntext")]
        public string Images { get; set; }
        public bool? Publish { get; set; }
        [Column("CEO")]
        public bool? Ceo { get; set; }
        [Column(TypeName = "ntext")]
        public string About { get; set; }
        [StringLength(300)]
        public string Avatar { get; set; }
        [StringLength(300)]
        public string Job { get; set; }
        public byte[] FingerTemplateBn { get; set; }
        public int? SkinnerIdInGroup { get; set; }
        [Column("isAccountLogin")]
        public int? IsAccountLogin { get; set; }
        [Column("isAppLogin")]
        public int? IsAppLogin { get; set; }
        public int? TeamId { get; set; }
        public bool? SalaryByPerson { get; set; }
        public bool? RequireEnroll { get; set; }
        [Column(TypeName = "date")]
        public DateTime? NgayTinhThamNien { get; set; }
        [Column("NganHang_SoTK")]
        [StringLength(50)]
        public string NganHangSoTk { get; set; }
        [Column("NganHang_ChiNhanh")]
        [StringLength(600)]
        public string NganHangChiNhanh { get; set; }
        [Column("NganHang_Ten")]
        [StringLength(300)]
        public string NganHangTen { get; set; }
        [Column("NguoiGioiThieuID")]
        public int? NguoiGioiThieuId { get; set; }
        public int? GroupLevelId { get; set; }
        [Column("S4MClassId")]
        public int? S4mclassId { get; set; }
        public bool? IsHoiQuan { get; set; }
        public int? LevelPoint { get; set; }
        [Column("CutTimeTB")]
        public int? CutTimeTb { get; set; }
        public string Note { get; set; }
        [Column("UngvienID")]
        public int? UngvienId { get; set; }
        [Column("NameCMT")]
        [StringLength(200)]
        public string NameCmt { get; set; }
        [Column("CMTimg1")]
        [StringLength(300)]
        public string Cmtimg1 { get; set; }
        [Column("CMTimg2")]
        [StringLength(300)]
        public string Cmtimg2 { get; set; }
        [Column("MST")]
        [StringLength(50)]
        public string Mst { get; set; }
        [StringLength(50)]
        public string NumberInsurrance { get; set; }
        [Column("NganHang_TenTK")]
        [StringLength(200)]
        public string NganHangTenTk { get; set; }
        [Column("PermissionID")]
        [StringLength(300)]
        public string PermissionId { get; set; }
        [Column("IDProvidedDate", TypeName = "date")]
        public DateTime? IdprovidedDate { get; set; }
        [Column("IDProviderLocale")]
        [StringLength(225)]
        public string IdproviderLocale { get; set; }
        [Column("IDHomeTown")]
        [StringLength(255)]
        public string IdhomeTown { get; set; }
        public int? StudentId { get; set; }
        public int? SourceId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        public double Score { get; set; }
        [StringLength(300)]
        public string AvartarBooking { get; set; }
        public bool? IsActiveBooking { get; set; }
        public int? CustomerServed { get; set; }
        [StringLength(100)]
        public string BestHairStyle { get; set; }
        public int? Seniority { get; set; }
        public int? CurlingDyed { get; set; }
        public bool? AdditionStaff { get; set; }
        [StringLength(100)]
        public string SpecialSkill { get; set; }
        public int? StynextLevelId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LeavingDate { get; set; }
        public string FavoriteImages { get; set; }

        [InverseProperty("Staff")]
        public virtual ICollection<StaffWorkingState> StaffWorkingState { get; set; }
    }
}