// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class StatisticRevenue
    {
        [Key]
        public long Id { get; set; }
        public int Month { get; set; }
        [Column(TypeName = "date")]
        public DateTime BillDate { get; set; }
        [StringLength(128)]
        public string ServiceCode { get; set; }
        [StringLength(128)]
        public string ServiceName { get; set; }
        [StringLength(128)]
        public string CustomerCode { get; set; }
        [StringLength(16)]
        public string Unit { get; set; }
        public int? SellTotal { get; set; }
        public double? Price { get; set; }
        public long? RevenueClassify { get; set; }
        public double? Turnover { get; set; }
        public double? ValueAddedTax { get; set; }
        public double? Total { get; set; }
        [Required]
        [StringLength(128)]
        public string SalonName { get; set; }
        public int SalonId { get; set; }
    }
}