// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class StaticCustomer
    {
        [Key]
        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public int? TotalMoney { get; set; }
    }
}