// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("Stylist4Men_BillCutFree")]
    public partial class Stylist4MenBillCutFree
    {
        [Key]
        public int Id { get; set; }
        public int? StudentId { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(600)]
        public string Images { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public int? ClassId { get; set; }
        [StringLength(100)]
        public string ImageStatusId { get; set; }
        [StringLength(600)]
        public string ImageChecked1 { get; set; }
        [StringLength(600)]
        public string ImageChecked2 { get; set; }
        [StringLength(600)]
        public string ImageChecked3 { get; set; }
        [StringLength(600)]
        public string ImageChecked4 { get; set; }
        [StringLength(600)]
        public string ErrorNote { get; set; }
        [StringLength(600)]
        public string NoteByStylist { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UploadImageTime { get; set; }
        public int? HairStyleId { get; set; }
    }
}