// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class StynextGroupMember
    {
        public int Id { get; set; }
        public int? StynextGroupId { get; set; }
        public int? StaffId { get; set; }
        public int? SalonId { get; set; }
        public bool? IsGroupLeader { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public bool? IsDeleted { get; set; }
        public bool AllowViewGroup { get; set; }
    }
}