// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class StynextLevelConfig
    {
        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string Name { get; set; }
        [StringLength(256)]
        public string Description { get; set; }
        public int? StaffType { get; set; }
        public double ServiceCommissionPercent { get; set; }
        public double RatioOvertimeHour { get; set; }
        public double RatioOvertimeDay { get; set; }
        public double GroupCommissionPercent { get; set; }
        public double FixedSalary { get; set; }
        public double RevenueTargetStandard { get; set; }
        [Column("R30TargetStandard")]
        public double R30targetStandard { get; set; }
        public double BehaveSalary { get; set; }
        public int? Type { get; set; }
    }
}