// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    public partial class TargetHighlightSalons
    {
        [Key]
        public int SalonId { get; set; }
        [Key]
        [StringLength(50)]
        public string TargetHighlightCode { get; set; }
        public double Range1Value { get; set; }
        public double Range2Value { get; set; }
        public double Range3Value { get; set; }
    }
}