// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("tbl_ListBack30Day")]
    public partial class TblListBack30Day
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string CusName { get; set; }
        [StringLength(20)]
        public string CusPhone { get; set; }
        public int? CusId { get; set; }
        public bool? Call { get; set; }
        [StringLength(500)]
        public string Note { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModyfiDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        public int? SalonId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}