// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Default.Tables
{
    [Table("Tbl_Permission_Map")]
    public partial class TblPermissionMap
    {
        [Key]
        [Column("mapID")]
        public int MapId { get; set; }
        [Column("pID")]
        public int? PId { get; set; }
        [Column("pName")]
        [StringLength(150)]
        public string PName { get; set; }
        [Column("mID")]
        public int? MId { get; set; }
        [Column("mName")]
        [StringLength(150)]
        public string MName { get; set; }
        [Column("aID")]
        [StringLength(200)]
        public string AId { get; set; }
        [Column("mapPublish")]
        public bool? MapPublish { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}