// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class CheckAttendance
    {
        public int Id { get; set; }
        public string OffReason { get; set; }
        public int? StudentId { get; set; }
        public DateTime? AttendanceDate { get; set; }
        public byte? IsAvaiable { get; set; }
        public byte? IsDelete { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ClassId { get; set; }
    }
}