// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class CustomerTag
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Tag { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string Code { get; set; }
    }
}