// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class DcustomerInfo
    {
        public int CustomerId { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerName { get; set; }
        public bool? CustomerGender { get; set; }
        public bool CustomerIsMarry { get; set; }
        public double CustomerScore { get; set; }
        public DateTime? CustomerBirthday { get; set; }
        public int? CustomerCareerId { get; set; }
        public int? TotalMoneyOfBill { get; set; }
        public DateTime? DateLastOfBill { get; set; }
        public DateTime? DateFirstOfBill { get; set; }
        public bool? UsedToPayByCard { get; set; }
        public int? TotalOfBill { get; set; }
    }
}