// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class FundSource
    {
        /// <summary>
        /// Nguồn tiền như salon, mỹ phẩm, đào tạo...
        /// </summary>
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        /// <summary>
        /// Đánh dấu,&apos;salon&apos; | kiểu nguồn là salon
        /// </summary>
        public string Hint { get; set; }
        /// <summary>
        /// Giá trị đi kèm cùng Hint
        /// </summary>
        public string Key { get; set; }
        public int? Order { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}