// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class InventoryData
    {
        public int Id { get; set; }
        /// <summary>
        /// Lượng sản phẩm tồn hiện tại (= Tồn nhập - Lượng bán). Sang ngày hôm sau, đây sẽ là giá trị tồn kho cuối ngày hôm trước
        /// </summary>
        public string InvenData { get; set; }
        public DateTime? IDate { get; set; }
        public int? SalonId { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime? CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}