// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    /// <summary>
    /// Danh sach tieu chi
    /// </summary>
    public partial class KpiCriterias
    {
        public int Id { get; set; }
        public int? StaffTypeId { get; set; }
        public string CriteriaName { get; set; }
        public string Formula { get; set; }
        public int? CalculatedWeight { get; set; }
        public string Point { get; set; }
        public byte? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        public string CriteriaCode { get; set; }
    }
}