// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class KpiDetailRatings
    {
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? Star1 { get; set; }
        public int? Star2 { get; set; }
        public int? Star3 { get; set; }
        public int? Star4 { get; set; }
        public int? Star5 { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}