// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class KpiDetailScsc
    {
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? SkillLevelId { get; set; }
        public int? SalonId { get; set; }
        public int? StaffTypeId { get; set; }
        public int? Diem0 { get; set; }
        public int? Diem4 { get; set; }
        public int? Diem5 { get; set; }
        public int? Diem6 { get; set; }
        public int? Diem7 { get; set; }
        public int? Diem8 { get; set; }
        public int? Diem9 { get; set; }
        public int? Diem10 { get; set; }
        public int? Diem11 { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}