// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class KpiDataMonths
    {
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? SkillLevelId { get; set; }
        public int? SalonId { get; set; }
        public int? StaffTypeId { get; set; }
        public int? TongBill { get; set; }
        public double? KhMoi { get; set; }
        public double? RatingTb { get; set; }
        public string KpiRatingTb { get; set; }
        public double? BillKhongAnh { get; set; }
        public string KpiBillKhongAnh { get; set; }
        public double? BillMoLech { get; set; }
        public string KpiBillMoLech { get; set; }
        public double? ScscTb { get; set; }
        public string KpiScscTb { get; set; }
        public double? GsLoi { get; set; }
        public string KpiGsLoi { get; set; }
        public double? Cmt { get; set; }
        public string KpiCmt { get; set; }
        public double? GtKhMoi { get; set; }
        public string KpiGtKhMoi { get; set; }
        public double? ChoLau { get; set; }
        public string KpiChoLau { get; set; }
        public int? SoKhachCanGoi { get; set; }
        public int? DaGoi { get; set; }
        public double? GoiNhacKhach { get; set; }
        public string KpiGoiNhacKhach { get; set; }
        public double? ThuongDv { get; set; }
        public double? ThuongSp { get; set; }
        public double? LuongCung { get; set; }
        public DateTime? KpiMonth { get; set; }
        public string KpiRange { get; set; }
        public double? KpiPoint { get; set; }
        public double? DoanhThu { get; set; }
        public string KpiDoanhThu { get; set; }
        public double? KpiDoanhThuDay { get; set; }
        public int? TotalRating { get; set; }
        public int? TotalPointScsc { get; set; }
        public int? TotalBillDanhGiaNotImageMoLech { get; set; }
        public double? TempSalary { get; set; }
        public double? QuyTrinh { get; set; }
        public string KpiQuyTrinh { get; set; }
        public double? Tip { get; set; }
    }
}