// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    /// <summary>
    /// diem chuyen doi
    /// </summary>
    public partial class KpiPointMappings
    {
        public int Id { get; set; }
        public string Point { get; set; }
        public int? Value { get; set; }
        public byte? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? UpdatedBy { get; set; }
        public double? SalaryPercent { get; set; }
    }
}