// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class Message
    {
        public int Id { get; set; }
        public DateTime? CreateTime { get; set; }
        public DateTime? DeleteTime { get; set; }
        public int? SenderId { get; set; }
        public int? ReceiverId { get; set; }
        public bool? IsAutoGenerate { get; set; }
        public string Text { get; set; }
        public int? Seq { get; set; }
        public string Sender { get; set; }
        public bool? Status { get; set; }
        public string Receiver { get; set; }
        public DateTime? UpdateTime { get; set; }
        public DateTime? SendTime { get; set; }
        public bool? IsDelete { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        public DateTime? SendSuccessTime { get; set; }
        public string Salon { get; set; }
        public int? SalonId { get; set; }
        public int? Type { get; set; }
    }
}