// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class MktCampaignUsed
    {
        public int CampaignId { get; set; }
        public int TotalUsed { get; set; }
    }
}