// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class Mobile
    {
        public int Id { get; set; }
        public int? AndroidVersion { get; set; }
        public string Iosversion { get; set; }
        public string AccessKey { get; set; }
        public string PrivateKey { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool IsDelete { get; set; }
        public string AppKey { get; set; }
        public int? AppReview { get; set; }
    }
}