// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class ProductUsedStatistic
    {
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? ServiceId { get; set; }
        public int? ProductId { get; set; }
        public double? QuantifyDefault { get; set; }
        public double? Quantify { get; set; }
        public string SlugKey { get; set; }
        public int? OrderNumber { get; set; }
        public DateTime? WorkDate { get; set; }
        public int? Status { get; set; }
        public bool IsDelete { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime? ModifiedTime { get; set; }
    }
}