// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class ProductReturnExplanation
    {
        public int Id { get; set; }
        public int? BillId { get; set; }
        public int? FlowProductId { get; set; }
        public int? SalonId { get; set; }
        public int? ProductId { get; set; }
        public int? InventoryId { get; set; }
        /// <summary>
        /// 0: Giải trình, 1: Đang chờ duyệt, 2: Chấp nhận, 3: Giải trình lại,4: Không chấp nhận, 5: Đã trả hàng
        /// </summary>
        public int? Status { get; set; }
        public string NoteSalon { get; set; }
        public string NoteKeToan { get; set; }
        public DateTime? CreateDateBill { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string CreatedUser { get; set; }
        public string UpdateUser { get; set; }
        public string CreateAcounter { get; set; }
        public DateTime? AcounterCreateDate { get; set; }
        public int? Quantity { get; set; }
        public int? NumberProductReturn { get; set; }
        public int? CountReturn { get; set; }
    }
}