// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class RatingAnswer
    {
        public int Id { get; set; }
        public string Answer { get; set; }
        public DateTime CreatedTime { get; set; }
        public bool? IsDeleted { get; set; }
    }
}