// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class SalonCamera
    {
        public int Id { get; set; }
        public int? SalonId { get; set; }
        public string IpAddress { get; set; }
        public int? Channel { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? Port { get; set; }
        public int? DepartmentId { get; set; }
        public DateTime? CreatedTime { get; set; }
        public bool? IsDeleted { get; set; }
        public string Description { get; set; }
        public DateTime? ModifiedTime { get; set; }
    }
}