// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class StaffWorkingData
    {
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public DateTime? WorkDate { get; set; }
        public int? TotalBill { get; set; }
        public int? WorkHours { get; set; }
    }
}