// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class StynextTarget
    {
        public int Id { get; set; }
        public int? SalonId { get; set; }
        public int? StaffId { get; set; }
        public int? StynextGroupId { get; set; }
        public DateTime Month { get; set; }
        public double RevenueTarget { get; set; }
        public double R30target { get; set; }
        public int? NumberStaffWorking { get; set; }
        public bool? IsDeleted { get; set; }
    }
}