// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class TargetHighlightSalons
    {
        public int SalonId { get; set; }
        public string TargetHighlightCode { get; set; }
        public double Range1Value { get; set; }
        public double Range2Value { get; set; }
        public double Range3Value { get; set; }
    }
}