// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class TargetHighlights
    {
        public string Code { get; set; }
        public string Description { get; set; }
    }
}