// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class TblPermissionDefaultPage
    {
        public int Id { get; set; }
        public int? MenuId { get; set; }
        public string MenuLink { get; set; }
        public int? PId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}