// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace S4M.Table
{
    public partial class UserStaff
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int? StaffId { get; set; }
        public DateTime? CreatedTime { get; set; }
    }
}