// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebDaihu.DataObject.Table
{
    public partial class Account
    {
        public int CustomerId { get; set; }
        public int AccountBalance { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public byte[] Verion { get; set; }
        public int? CashBalance { get; set; }
        public decimal? DiscountPercent { get; set; }
        public bool? MigrateStatus { get; set; }
    }
}