// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WebDaihu.DataObject.Table
{
    public partial class AccountLog
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Token { get; set; }
        public int ModBalance { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string TransactionId { get; set; }
        public int? CurrentAccBalance { get; set; }
        public string Channel { get; set; }
        public int? BillId { get; set; }
        public string UserAction { get; set; }
        public int? ModCashBalance { get; set; }
        public int? CurrentCashBalance { get; set; }
        public decimal? CurrentDiscountPercent { get; set; }
    }
}