// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebTest.DataObject.EntityTypes
{
    public partial class Account
    {
        [Key]
        public int CustomerId { get; set; }
        public int AccountBalance { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        [Required]
        public byte[] Verion { get; set; }
        public int? CashBalance { get; set; }
        [Column(TypeName = "decimal(13, 10)")]
        public decimal? DiscountPercent { get; set; }
        public bool? MigrateStatus { get; set; }
    }
}