// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebTest.DataObject.EntityTypes
{
    public partial class AccountLog
    {
        [Key]
        public int Id { get; set; }
        public int CustomerId { get; set; }
        [StringLength(1024)]
        public string Token { get; set; }
        public int ModBalance { get; set; }
        public bool? IsDelete { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        [StringLength(100)]
        public string TransactionId { get; set; }
        public int? CurrentAccBalance { get; set; }
        [StringLength(20)]
        public string Channel { get; set; }
        public int? BillId { get; set; }
        [StringLength(30)]
        public string UserAction { get; set; }
        public int? ModCashBalance { get; set; }
        public int? CurrentCashBalance { get; set; }
        [Column(TypeName = "decimal(13, 10)")]
        public decimal? CurrentDiscountPercent { get; set; }
    }
}