// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class Appointment
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string AppointmentCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AppointmentTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(50)]
        public string CustomerCode { get; set; }
        public bool? CustomerNoInfo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }
        public bool? IsPending { get; set; }
        public bool? IsCancel { get; set; }
        public byte? IsDelete { get; set; }
        public int? StylistId { get; set; }
        public int? SalonId { get; set; }
        public int? SellerId { get; set; }
        [Column("PDFBillCode")]
        [StringLength(50)]
        public string PdfbillCode { get; set; }
        public bool? IsNotify { get; set; }
        public int? TeamId { get; set; }
        public string ServiceIds { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}