// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class Authorization
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string UserType { get; set; }
        [StringLength(50)]
        public string Uid { get; set; }
        [StringLength(50)]
        public string UserUid { get; set; }
        [StringLength(50)]
        public string DeviceUid { get; set; }
        [StringLength(50)]
        public string ApplicationUid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeleteTime { get; set; }
        [StringLength(50)]
        public string DeviceType { get; set; }
        [StringLength(250)]
        public string DeviceName { get; set; }
        [StringLength(500)]
        public string Token { get; set; }
        [StringLength(50)]
        public string TokenAlg { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TokenExp { get; set; }
        [StringLength(25)]
        public string TokenType { get; set; }
        [StringLength(50)]
        public string TokenIss { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsForever { get; set; }
        public bool? IsDelete { get; set; }
        [StringLength(50)]
        public string AppVersion { get; set; }
    }
}