// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Bill_WaitAtSalon")]
    public partial class BillWaitAtSalon
    {
        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string CustomerPhone { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public int? SalonId { get; set; }
        public bool? IsPending { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}