// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class BookHour
    {
        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string Hour { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Day { get; set; }
        public int? UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? Publish { get; set; }
        public byte? IsDelete { get; set; }
        public int? Slot { get; set; }
        [Column(TypeName = "time(0)")]
        public TimeSpan? HourFrame { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DatedBook { get; set; }
        public int? SalonId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}