// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class Brands
    {
        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        public string TenThuongHieu { get; set; }
        [Column(TypeName = "ntext")]
        public string Mota { get; set; }
        [StringLength(250)]
        public string XuatXu { get; set; }
        [StringLength(250)]
        public string Images { get; set; }
        public bool? Status { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}