// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class ConfigMembership
    {
        [Key]
        public int Id { get; set; }
        public int? ProductMemberId { get; set; }
        public int? IdServiceOrProduct { get; set; }
        public int? PriceMember { get; set; }
        public int? Type { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsPublish { get; set; }
    }
}