// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("DCustomerProduct")]
    public partial class DcustomerProduct
    {
        [Key]
        public int IdCustomerProduct { get; set; }
        public int CustomerId { get; set; }
        public int BillId { get; set; }
        public int ProductId { get; set; }
        public int ProductPrice { get; set; }
        public int ProductQuantity { get; set; }
        public int VoucherPercent { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateOfBill { get; set; }
        public int SalonId { get; set; }
        public int? SellerId { get; set; }
    }
}