// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class Device
    {
        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string DeviceName { get; set; }
        [Column("ImeiOrMacIP")]
        [StringLength(300)]
        public string ImeiOrMacIp { get; set; }
        public int? OwnerType { get; set; }
        public int? OwnerId { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(300)]
        public string UniqueKey { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDelete { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}