// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class FlowTimeKeepingHis
    {
        [Key]
        public int Id { get; set; }
        public int StaffId { get; set; }
        public int SalonId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public byte? IsDelete { get; set; }
        public int? DoUserId { get; set; }
        public string Note { get; set; }
        public int? WorkHour { get; set; }
        public int? Type { get; set; }
        public bool? IsEnroll { get; set; }
        public int? WorkTimeId { get; set; }
        [StringLength(200)]
        public string HourIds { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckinFirstTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckoutLastTime { get; set; }
        public int? DelayTime { get; set; }
        public bool? CheckEnroll { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        public bool? Use2ndSubHours { get; set; }
    }
}