// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Fund_OffenItem")]
    public partial class FundOffenItem
    {
        /// <summary>
        /// Bảng danh sách các chi tiêu thường xuyên
        /// </summary>
        [Key]
        public int Id { get; set; }
        [StringLength(600)]
        public string Title { get; set; }
        public string Description { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        /// <summary>
        /// Lượng tiền sử dụng trong khoản thu/chi này
        /// </summary>
        public int? Money { get; set; }
        public int? Order { get; set; }
        public bool? IsReceipt { get; set; }
        public int? SourceId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}