// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Fund_Import")]
    public partial class FundImport
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Id tài khoản : Quỹ tiền mặt hay tài khoản ngân hàng
        /// </summary>
        public int? AccountTypeId { get; set; }
        /// <summary>
        /// Id nguồn
        /// </summary>
        public int? SourceId { get; set; }
        /// <summary>
        /// Trạng thái có phải thu hay không. True | Thu, False | Chi
        /// </summary>
        public bool? IsReceipt { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public string Note { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ImportDate { get; set; }
        public int? TotalMoney { get; set; }
        public int? OffenItemId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}