// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Inventory_Data")]
    public partial class InventoryData
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Lượng sản phẩm tồn hiện tại (= Tồn nhập - Lượng bán). Sang ngày hôm sau, đây sẽ là giá trị tồn kho cuối ngày hôm trước
        /// </summary>
        public string InvenData { get; set; }
        [Column("iDate", TypeName = "date")]
        public DateTime? IDate { get; set; }
        public int? SalonId { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}