// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class IvInventory
    {
        [Key]
        public int Id { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        public int Type { get; set; }
        public int? SalonId { get; set; }
        public int? StaffId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDelete { get; set; }
        public int ParentId { get; set; }
        public int DeliveryHoursAfterOrderDate { get; set; }
        public int? RoutingId { get; set; }
        [Column("OrderRoutingID")]
        public int? OrderRoutingId { get; set; }
        [Column(TypeName = "decimal(10, 1)")]
        public decimal? ShippingNum { get; set; }
    }
}