// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class IvProductQuantify
    {
        [Key]
        public int Id { get; set; }
        public int? InventoryId { get; set; }
        public int? ServiceId { get; set; }
        public int? ProductId { get; set; }
        public int? StaffType { get; set; }
        public double? Volume { get; set; }
        public int? TotalNumberService { get; set; }
        public double? Quantify { get; set; }
        [Required]
        public bool? IsPublish { get; set; }
        public bool IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
    }
}