// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class MktCampaignUsed
    {
        [Key]
        public int CampaignId { get; set; }
        public int TotalUsed { get; set; }
    }
}