// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class MktCampaignService
    {
        [Key]
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int CampaignId { get; set; }
        public double DiscountPercent { get; set; }
        public double ServicePrice { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public bool IsDelete { get; set; }
        public int? TimesUsed { get; set; }
        public int? MoneyPrePaid { get; set; }
        public int? MoneyDeductions { get; set; }
    }
}