// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class NotificationUsers
    {
        [Key]
        public int Id { get; set; }
        public int? NotiId { get; set; }
        public int? UserId { get; set; }
        [StringLength(50)]
        public string SlugKey { get; set; }
        public int? Status { get; set; }
        [Required]
        public bool? IsPublish { get; set; }
        public bool IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
    }
}