// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class OrderRecruitingStaff
    {
        [Key]
        public int Id { get; set; }
        public int? RegionId { get; set; }
        public int? SalonId { get; set; }
        public int? DepartmentId { get; set; }
        public int? CreatorId { get; set; }
        public int? StaffId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StaffDate { get; set; }
        public int? Type { get; set; }
        public int? Quantity { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Needed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Completed { get; set; }
        public int? Status { get; set; }
        public int? ReasonRevoke { get; set; }
        public int? CandidateId { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDelete { get; set; }
        public bool? HavingTry { get; set; }
    }
}