// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class OrderBrokenDeviceHandling
    {
        [Key]
        public int Id { get; set; }
        public int? RegionId { get; set; }
        public int? SalonId { get; set; }
        public int? OrderStaffId { get; set; }
        public int? CategoryId { get; set; }
        public int? TeamId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BrokenDate { get; set; }
        [StringLength(1000)]
        public string ImagesBroken { get; set; }
        [StringLength(500)]
        public string DescriptionBroken { get; set; }
        public int? LevelPriority { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DesiredDeadline { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CorrectDeadline { get; set; }
        public int? StaffIdHandling { get; set; }
        public int? StatusHandling { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompleteDate { get; set; }
        [StringLength(1000)]
        public string ImageHandling { get; set; }
        public int? ProcessHandling { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StatusCheckTime { get; set; }
        public int? StatusCheck { get; set; }
        [StringLength(500)]
        public string Note { get; set; }
        public int? ReasonRevoke { get; set; }
        [StringLength(500)]
        public string NoteRevoke { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDelete { get; set; }
        [StringLength(500)]
        public string HandlingNote { get; set; }
    }
}