// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class PermissionMenu
    {
        [Key]
        public int Id { get; set; }
        public int? Pid { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public string Description { get; set; }
        [StringLength(450)]
        public string Title { get; set; }
        [StringLength(450)]
        public string Link { get; set; }
        [StringLength(300)]
        public string Path { get; set; }
        [StringLength(200)]
        public string PageId { get; set; }
        public string IconImage { get; set; }
        [StringLength(50)]
        public string ClassTag { get; set; }
        public bool? IsDelete { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}