// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("QLKho_SalonOrder")]
    public partial class QlkhoSalonOrder
    {
        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string BillCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public bool? IsDelete { get; set; }
        public int? SalonId { get; set; }
        public int? StatusId { get; set; }
        [StringLength(600)]
        public string NoteSalon { get; set; }
        [StringLength(600)]
        public string NoteKho { get; set; }
        public string ProductIds { get; set; }
        [Column(TypeName = "date")]
        public DateTime? OrderDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExportTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ReceivedTime { get; set; }
        public int? Order { get; set; }
        public int? CheckCosmetic { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}