// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class RatingDetail
    {
        [Key]
        public int Id { get; set; }
        public int? BillId { get; set; }
        [Column("RatingReasonId ")]
        public string RatingReasonId { get; set; }
        public int? RatingValue { get; set; }
        public int? RatingBonusValue { get; set; }
        public int? StarNumber { get; set; }
        public bool? Isdelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public bool? Iscomeback { get; set; }
        public int? Version { get; set; }
        public int? StepNumber { get; set; }
        public bool? RatingReason1 { get; set; }
        public bool? RatingReason2 { get; set; }
        public bool? RatingReason3 { get; set; }
        public bool? RatingReason4 { get; set; }
        public bool? RatingReason5 { get; set; }
        public bool? RatingReason6 { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        [Column("isAuto")]
        public bool? IsAuto { get; set; }
        public long? OrderNumber { get; set; }
        public bool? RattingReason7 { get; set; }
        [StringLength(200)]
        public string SatisfactionReasons { get; set; }
        public bool? RatingReason8 { get; set; }
    }
}