// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class SalonProduct
    {
        [Key]
        public int Id { get; set; }
        public int SalonId { get; set; }
        public int? InventoryId { get; set; }
        public int ProductId { get; set; }
        public int? InventoryType { get; set; }
        public bool? IsUse { get; set; }
        public int? Price { get; set; }
        public int? Discount { get; set; }
        [Column("isFrezze")]
        public bool IsFrezze { get; set; }
    }
}