// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("SCSC_Category")]
    public partial class ScscCategory
    {
        [Key]
        [Column("ID_SCSC_Cate")]
        public int IdScscCate { get; set; }
        [Column("SCSC_Cate_Name")]
        [StringLength(200)]
        public string ScscCateName { get; set; }
        [Column("SCSC_Cate_Des")]
        public string ScscCateDes { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiledTime { get; set; }
        [Column("SCSC_Cate_IDCate")]
        public int? ScscCateIdcate { get; set; }
        [Column("SCSC_Cate_Image")]
        public string ScscCateImage { get; set; }
        [Column("SCSC_Cate_Image_Active")]
        public string ScscCateImageActive { get; set; }
        [Column("SCSC_Cate_Point")]
        public int? ScscCatePoint { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}