// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("SCSC_CheckError")]
    public partial class ScscCheckError
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Key]
        [Column("BillService_ID")]
        public int BillServiceId { get; set; }
        public bool? ImageError { get; set; }
        public string NoteError { get; set; }
        [Column("Shape_ID")]
        public int? ShapeId { get; set; }
        [Column("ConnectTive_ID")]
        public int? ConnectTiveId { get; set; }
        [Column("SharpNess_ID")]
        public int? SharpNessId { get; set; }
        [Column("ComPlatetion_ID")]
        public int? ComPlatetionId { get; set; }
        public bool? Publish { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiledDate { get; set; }
        [Column("TotalPointSCSC")]
        public int? TotalPointScsc { get; set; }
        [Column("MaxPoint_Shap_ID")]
        public int? MaxPointShapId { get; set; }
        [Column("MaxPoint_Connective_ID")]
        public int? MaxPointConnectiveId { get; set; }
        [Column("MaxPoint_SharpNess_ID")]
        public int? MaxPointSharpNessId { get; set; }
        [Column("MaxPoint_ComPlatetion_ID")]
        public int? MaxPointComPlatetionId { get; set; }
        public int? PointError { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        public bool AutomaticScore { get; set; }
        [Column("HairTip_ID")]
        public int? HairTipId { get; set; }
        [Column("HairRoot_ID")]
        public int? HairRootId { get; set; }
        [Column("HairWaves_ID")]
        public int? HairWavesId { get; set; }
        [Column("TotalPointSCSCCurling")]
        public int? TotalPointScsccurling { get; set; }
        public bool? ImageErrorCurling { get; set; }
        public int? CreativeId { get; set; }
    }
}