// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class ShineMemberUpdate
    {
        [Key]
        public int Id { get; set; }
        public int? OldCustomerId { get; set; }
        [StringLength(20)]
        public string OldCustomerPhone { get; set; }
        public int? NewCustomerId { get; set; }
        [StringLength(20)]
        public string NewCustomerPhone { get; set; }
        public int? UserUpdate { get; set; }
        [StringLength(350)]
        public string NoteUpdate { get; set; }
        public int? Confirm { get; set; }
        public int? ReasonId { get; set; }
        [StringLength(350)]
        public string TelesaleNote { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public bool? IsDelete { get; set; }
        public int? BillId { get; set; }
        public int? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TimeConfirm { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TimeChange { get; set; }
        public int? UserConfirm { get; set; }
        public int? UserUpdateChange { get; set; }
    }
}