// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Skin_Attribute_Product")]
    public partial class SkinAttributeProduct
    {
        [Key]
        public int Id { get; set; }
        [Column("Skin_AttributeId")]
        public int? SkinAttributeId { get; set; }
        [StringLength(250)]
        public string ProductId { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "ntext")]
        public string Description { get; set; }
        [StringLength(250)]
        public string Title { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}