// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class StaffErrorSpecailCus
    {
        [Key]
        public int Id { get; set; }
        [Column("SpecialCus_ID")]
        public int? SpecialCusId { get; set; }
        [Column("Staff_ID")]
        public int? StaffId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Createdate { get; set; }
        public bool? IsDelete { get; set; }
        public bool? Publish { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}