// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Staff_Ranking")]
    public partial class StaffRanking
    {
        [Key]
        [Column("StaffID")]
        public int StaffId { get; set; }
        [Column("GIAOTIEP_DONGNGHIEP")]
        public int? GiaotiepDongnghiep { get; set; }
        [Column("GIAOTIEP_KHACHHANG")]
        public int? GiaotiepKhachhang { get; set; }
        [Column("GIAOTIEP_QUANLY")]
        public int? GiaotiepQuanly { get; set; }
        [Column("TUVANTOC_KHACHHANG")]
        public int? TuvantocKhachhang { get; set; }
        [Column("TUVANTOC_DONGNGHIEP")]
        public int? TuvantocDongnghiep { get; set; }
        [Column("TUVAN_HOACHAT")]
        public int? TuvanHoachat { get; set; }
        [Column("TUVAN_MYPHAM")]
        public int? TuvanMypham { get; set; }
        [Column("NGOAIHINH")]
        public int? Ngoaihinh { get; set; }
    }
}