// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Staff_Mistake")]
    public partial class StaffMistake
    {
        [Key]
        public int Id { get; set; }
        public int? StaffId { get; set; }
        public int? Point { get; set; }
        [Column(TypeName = "ntext")]
        public string Description { get; set; }
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        public string Images { get; set; }
        public int? FormMissTakeId { get; set; }
        [StringLength(255)]
        public string Note { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}