// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("statictisReportOperation")]
    public partial class StatictisReportOperation
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Id của salon
        /// </summary>
        public int SalonId { get; set; }
        /// <summary>
        /// Tên viết tắt của salon
        /// </summary>
        [Column("salonName")]
        [StringLength(500)]
        public string SalonName { get; set; }
        /// <summary>
        /// Tổng doanh thu của salon
        /// </summary>
        [Column("totalIncome")]
        public double TotalIncome { get; set; }
        /// <summary>
        /// tổng doanh thu dịch vụ
        /// </summary>
        [Column("totalServiceInCome")]
        public double TotalServiceInCome { get; set; }
        /// <summary>
        /// tổng doanh thu mỹ phẩm
        /// </summary>
        [Column("totalProductIncome")]
        public double TotalProductIncome { get; set; }
        /// <summary>
        /// số giờ làm việc của stylist
        /// </summary>
        [Column("worktimeStylist")]
        public double WorktimeStylist { get; set; }
        /// <summary>
        /// số bill dịch vụ
        /// </summary>
        [Column("numberOfTurns")]
        public int NumberOfTurns { get; set; }
        /// <summary>
        /// Số khách cũ
        /// </summary>
        [Column("numberCustomerOld")]
        public int NumberCustomerOld { get; set; }
        /// <summary>
        /// bill không ảnh
        /// </summary>
        [Column("numberBillNotImg")]
        public int NumberBillNotImg { get; set; }
        /// <summary>
        /// bill không hài lòng
        /// </summary>
        [Column("numberBillKHL")]
        public int NumberBillKhl { get; set; }
        /// <summary>
        /// tổng số sao đánh giá
        /// </summary>
        [Column("totalStarNumber")]
        public int TotalStarNumber { get; set; }
        /// <summary>
        /// Số lỗi giám sát
        /// </summary>
        [Column("numberErrorMonitoring")]
        public int NumberErrorMonitoring { get; set; }
        /// <summary>
        /// số lượng stylist chấm công
        /// </summary>
        [Column("numberStylistTimekeeping")]
        public int NumberStylistTimekeeping { get; set; }
        /// <summary>
        /// số lượng skinner chấm công
        /// </summary>
        [Column("numberSkinnerTimekeeping")]
        public int NumberSkinnerTimekeeping { get; set; }
        /// <summary>
        /// Số lượng stylist đi thuộc biên chế cty
        /// </summary>
        [Column("numberStylist")]
        public int NumberStylist { get; set; }
        /// <summary>
        /// Số lượng hủy book
        /// </summary>
        [Column("numberCanleBooking")]
        public int NumberCanleBooking { get; set; }
        /// <summary>
        /// Số lượng xóa book
        /// </summary>
        [Column("numberDeleteBooking")]
        public int NumberDeleteBooking { get; set; }
        /// <summary>
        /// Số giờ tăng ca của stylist
        /// </summary>
        [Column("overtimeHoursStylist")]
        public int OvertimeHoursStylist { get; set; }
        /// <summary>
        /// tổng số slot được book
        /// </summary>
        [Column("numberSlotBooking")]
        public int NumberSlotBooking { get; set; }
        /// <summary>
        /// khách dịch vụ đặt trước và checkout
        /// </summary>
        [Column("numberBooking")]
        public int NumberBooking { get; set; }
        /// <summary>
        /// khách booking inline checkout
        /// </summary>
        [Column("numberBookingBefor")]
        public int NumberBookingBefor { get; set; }
        /// <summary>
        /// Bill Khach phai cho lau &gt; 15 phút
        /// </summary>
        [Column("numberBillWaited")]
        public int NumberBillWaited { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WorkDate { get; set; }
        [Column("isDelete")]
        public bool? IsDelete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// bill danh gia 1 sao
        /// </summary>
        [Column("numberBill1Star")]
        public int NumberBill1Star { get; set; }
        /// <summary>
        /// bill danh giá 2 sao
        /// </summary>
        [Column("numberBill2Star")]
        public int NumberBill2Star { get; set; }
        /// <summary>
        /// bill danh gia 3 sao
        /// </summary>
        [Column("numberBill3Star")]
        public int NumberBill3Star { get; set; }
        /// <summary>
        /// bill danh gia 4 sao
        /// </summary>
        [Column("numberBill4Star")]
        public int NumberBill4Star { get; set; }
        /// <summary>
        /// bill danh gia 5 sao
        /// </summary>
        [Column("numberBill5Star")]
        public int NumberBill5Star { get; set; }
        /// <summary>
        /// tong so bill dich vu ShineCombo
        /// </summary>
        [Column("totalShineCombo")]
        public int TotalShineCombo { get; set; }
        /// <summary>
        /// tong bill dịch vụ Kid Combo
        /// </summary>
        [Column("totalKidCombo")]
        public int TotalKidCombo { get; set; }
        /// <summary>
        /// tong bill dich vu dưỡng Protein
        /// </summary>
        [Column("totalProtein")]
        public int TotalProtein { get; set; }
        /// <summary>
        /// tong so dich vu Tay Da Chet
        /// </summary>
        [Column("totalMask")]
        public int TotalMask { get; set; }
        /// <summary>
        /// tong so dich vu đắp mặt lạ
        /// </summary>
        [Column("totalExFoliation")]
        public int TotalExFoliation { get; set; }
        /// <summary>
        /// tong so bill su dụng group uon + duoi
        /// </summary>
        [Column("totalGroupUonDuoi")]
        public int TotalGroupUonDuoi { get; set; }
        /// <summary>
        /// tong so luong group Color ComBo ( Nhuộm )
        /// </summary>
        [Column("totalGroupColorCombo")]
        public int TotalGroupColorCombo { get; set; }
    }
}