// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class StaticExpense
    {
        [Key]
        public int Id { get; set; }
        public int? SalonId { get; set; }
        [StringLength(20)]
        public string ShortName { get; set; }
        public double? TotalSales { get; set; }
        public double? TotalServiceProfit { get; set; }
        public double? TotalCosmeticProfit { get; set; }
        public double? ProductSalary { get; set; }
        public double? TotalProductPrice { get; set; }
        public double? TotalStaffSalary { get; set; }
        public double? TotalProductUsed { get; set; }
        public double? OtherExpense { get; set; }
        [Column("MKTExpense")]
        public double? Mktexpense { get; set; }
        [Column("ITExpense")]
        public double? Itexpense { get; set; }
        public double? DayExpense { get; set; }
        [Column("LNGAll30shine")]
        public double? Lngall30shine { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
        public double? TotalIncomeAfterTax { get; set; }
        public double? NumberOfTurns { get; set; }
        public double? TotalTransactionPerCus { get; set; }
        public double? TotalServicePerCus { get; set; }
        public double? TotalProductPerCus { get; set; }
        public double? DirectFee { get; set; }
        public double? SalaryServicePerServiceIncome { get; set; }
        public double? TotalProductCapital { get; set; }
        [Column("TotalPayOffKCS")]
        public double? TotalPayOffKcs { get; set; }
        public double? TotalDailyCostInventory { get; set; }
        public double? ElectricityAndWaterBill { get; set; }
        public double? SalonFee { get; set; }
        public double? RentWithTax { get; set; }
        public double? CapitalSpending { get; set; }
        [Column("TotalSMSExpenses")]
        public double? TotalSmsexpenses { get; set; }
        public double? ShippingExpend { get; set; }
        public double? InternetAndPhoneBill { get; set; }
        public double? SocialInsuranceAndFixedCost { get; set; }
        public double? Tax { get; set; }
        public double? IncomeTaxes { get; set; }
        public double? SalonUnplannedSpending { get; set; }
        public double? ManageFee { get; set; }
        public double? OfficeRentAndServiceCose { get; set; }
        public double? OfficeStaffSalary { get; set; }
        public double? SalesSalary { get; set; }
        public double? OfficeStaffSocialInsurance { get; set; }
        public double? UnplannedSpending { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifyTime { get; set; }
        public double? Compensation { get; set; }
        public double? TotalOtherIncome { get; set; }
        [Column("TotalSMDistributionToday")]
        public double TotalSmdistributionToday { get; set; }
        [Column("TotalProductSM")]
        public double TotalProductSm { get; set; }
        [Column("TotalSMDistributon")]
        public double TotalSmdistributon { get; set; }
        public double TotalNetRevenue { get; set; }
        public double TotalSecurityCheckoutSalary { get; set; }
    }
}