// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class StaticOperate
    {
        [Key]
        public int Id { get; set; }
        public int? SalonId { get; set; }
        public double? Stylist { get; set; }
        public double? Skinner { get; set; }
        public double? PerfectBill { get; set; }
        public double? GoodBill { get; set; }
        public double? BadBill { get; set; }
        public double? OldCustomer { get; set; }
        public double? BookingOnline { get; set; }
        public double? BillOver15m { get; set; }
        public double? BillUnder15m { get; set; }
        public double? BillTimeNull { get; set; }
        public double? BillHasImage { get; set; }
        public double? ProfitByHour { get; set; }
        public double? ProfitByDay { get; set; }
        public double? ServiceByDay { get; set; }
        public double? ServiceByHour { get; set; }
        [Column(TypeName = "date")]
        public DateTime? WorkDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}