// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Tbl_Config")]
    public partial class TblConfig
    {
        [Key]
        public int Id { get; set; }
        [StringLength(300)]
        public string Label { get; set; }
        [StringLength(600)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Hint { get; set; }
        [StringLength(50)]
        public string Key { get; set; }
        public string Value { get; set; }
        public string Meta { get; set; }
        public int? IsDelete { get; set; }
        public int? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}