// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Tbl_EmailReport")]
    public partial class TblEmailReport
    {
        [Key]
        public int Id { get; set; }
        [StringLength(300)]
        public string Name { get; set; }
        [Required]
        [StringLength(300)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Permission { get; set; }
        public int? SalonId { get; set; }
        public byte? IsDelete { get; set; }
        public int? Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}