// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("Tbl_Permission")]
    public partial class TblPermission
    {
        [Key]
        [Column("pID")]
        public int PId { get; set; }
        [Column("pName")]
        [StringLength(150)]
        public string PName { get; set; }
        [Column("pTitle")]
        [StringLength(150)]
        public string PTitle { get; set; }
        [Column("pOder")]
        public int? POder { get; set; }
        [Column("pPublish")]
        public bool? PPublish { get; set; }
        [Column("pCreatedDate", TypeName = "datetime")]
        public DateTime? PCreatedDate { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}