// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    public partial class TeamService
    {
        [Key]
        public int Id { get; set; }
        [StringLength(300)]
        public string Name { get; set; }
        public string Description { get; set; }
        public byte? IsDelete { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? Publish { get; set; }
        public byte? Status { get; set; }
        [StringLength(50)]
        public string Color { get; set; }
        [StringLength(50)]
        public string Account { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        public bool? IsLogin { get; set; }
        public bool? IsOff { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}