// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Database.Thailan.Tables
{
    [Table("TrackingWeb_Data")]
    public partial class TrackingWebData
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("EventID")]
        public int? EventId { get; set; }
        [StringLength(200)]
        public string Value { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [StringLength(50)]
        public string TokenKey { get; set; }
        [StringLength(200)]
        public string Meta { get; set; }
        [Column("VersionID")]
        public int? VersionId { get; set; }
        public Guid? Uid { get; set; }
        public byte? MigrateStatus { get; set; }
    }
}